### ISSUE TITLE
Externalizing DB connection strings

### ISSUE THREAD

**Issue by lapido** [Ahmedsaka/crud-with-sp#2]
Your connection strings are hard-coded in your application.

The connection strings are expected to be in your application.properties file.

![Capture](https://user-images.githubusercontent.com/12137070/77302346-7d1a1180-6cf1-11ea-8803-67fd6f32b559.PNG)

And again the application is not failing fast for failure to DB connection; failure only happens when I try to access an endpoint. Failure should have happened during application startup.

**Comment by Ahmedsaka** [comment]
Thanks a lot Victor, changes have been made to correct this issue. Kindly check my recent
![config](https://user-images.githubusercontent.com/29652090/77309246-983e4e80-6cfc-11ea-98c6-1c317a07f88d.JPG)
![properties](https://user-images.githubusercontent.com/29652090/77309367-d0de2800-6cfc-11ea-83ed-19e3eba7f168.JPG)
